#!/bin/bash



#External Parameters
extpar_dir=/project/pr04/extpar-HPC
extpar_file_lm_c=extpar_12km_europe_771x771.nc
extpar_file_lm_f=extpar_2km_europe_2313x2313.nc


if [ "${LM_YYYY_BEGIN}" -le "2005" ];then
  #echo "They're equal";
  folder_in_o3=historical/
  str_name=caf_historical_r1i1p1_T63L47_
else 
  folder_in_o3=rcp85/
  str_name=caf_rcp85_r1i1p1_T63L47_
fi

cp /store/c2sm/pr04/jvergara/invar_echam6_historical_r1i1p1-LR_T63L47.nc output


cat > job <<EOF_job
#!/bin/bash -l
#
#SBATCH --job-name=get_data
#SBATCH --output=job.out
#SBATCH --time=01:00:00
#SBATCH --ntasks=1
#SBATCH --partition=xfer
module unload xalt

#Create Output directory
if [ ! -d ../input/ifs2lm ] ; then mkdir -p ../input/ifs2lm ; fi

#Copy External Parameters
if [ ! -f ../1_ifs2lm/$extpar_file_lm_c ] ; then /bin/cp $extpar_dir/$extpar_file_lm_c ../1_ifs2lm/input ; fi
if [ ! -f ../3_lm2lm/$extpar_file_lm_f  ] ; then /bin/cp $extpar_dir/$extpar_file_lm_f ../3_lm2lm/input  ; fi


scp vejesus@o3.ethz.ch:/cordex_driving/MPI-ESM-LR/${folder_in_o3}*${LM_YYYY_BEGIN}${LM_MM_BEGIN}* output/

cd output
tar -xvf ${str_name}${LM_YYYY_BEGIN}${LM_MM_BEGIN}.tar  

#ssh ela 'sleep 20 &&ls>test_ls &'

pwd
cd ..
#if [-f do]
#then
#    ./run_daint.sh
#    rm do
#fi

#./run_daint.sh
EOF_job

#On daint use xfer queue
if [[ $HOST == daint* ]]; then
  sed -i '/#SBATCH --partition=normal/c\#SBATCH  --partition=xfer' job
fi

# clean away old *.out files
\rm -f *.out 2>/dev/null
chmod u+x job
# submit job
jobid=`sbatch -C gpu -n 1 job | sed 's/Submitted batch job //g'`

if [ $? -eq 0 -a -n "${jobid}" ]; then
  echo "${jobid}" > .jobid
  echo "${jobid}"
else
  exit 1
fi

